### ISSUE TITLE
parameters in azure-pipelines does not work

### ISSUE THREAD

**Issue by jyotirmay123** [asottile/azure-pipeline-templates#79]
Hi,

I was trying to use the pre-commit azure pipeline and it is broken now I guess.
Azure pipeline complains about the way parameters are defined in it.

I changed it to this below and it works. Hope if all look good, kindly change.

```yaml
parameters:
  - name: ruby
    type: string
    default: '>= 2.4'
  - name: python
    type: string
    default: '3.9'

jobs:
- job: precommit
  pool:
    vmImage: ubuntu-latest
  variables:
    PRE_COMMIT_HOME: $(Pipeline.Workspace)/pre-commit-cache

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: ${{parameters.python}}
  - task: UseRubyVersion@0
    inputs:
      versionSpec: ${{parameters.ruby}}

  - script: |
      echo "##vso[task.setvariable variable=PY]$(python -VV)"
      echo "##vso[task.setvariable variable=RB]$(ruby -v)"
    displayName: set version variables

  - task: CacheBeta@0
    inputs:
      key: pre-commit | "4" | .pre-commit-config.yaml | "$(PY)" | "$(RB)"
      path: $(PRE_COMMIT_HOME)

  - script: python -m pip install --upgrade pre-commit
    displayName: install pre-commit
  - script: pre-commit run --all-files --show-diff-on-failure
    displayName: run pre-commit

```

**Comment by asottile** [comment]
works fine for me: #80

report your actual bug rather than prescribing a solution

**Comment by jyotirmay123** [comment]
Sorry for the proposal.

I tried to use the pre-commit pipeline as it is in Azure and it throws below error:

`/azure-pipelines.yml (Line: 2, Col: 3): A mapping was not expected`

My copied pipeline below: (Just removed ruby dependency)

```yaml
parameters:
  python: '3.9'

jobs:
  - job: precommit
    pool:
      vmImage: ubuntu-latest
    variables:
      PRE_COMMIT_HOME: $(Pipeline.Workspace)/pre-commit-cache

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: ${{parameters.python}}

      - script: |
          echo "##vso[task.setvariable variable=PY]$(python -VV)"
        displayName: set version variables

      - task: CacheBeta@0
        inputs:
          key: pre-commit | "4" | .pre-commit-config.yaml | "$(PY)"
          path: $(PRE_COMMIT_HOME)

      - script: python -m pip install --upgrade pre-commit
        displayName: install pre-commit
      - script: pre-commit run --all-files --show-diff-on-failure
        displayName: run pre-commit


```
